import type { Unit } from "../schema";

export const unit01: Unit = {
  id: "u-01",
  title: "First contact",
  phase: 1,
  level: "A2",
  summary:
    "Greet people, introduce yourself, and order in a café — your first real German conversations.",
  prerequisites: [],
  lessons: [
    // -------------------------------------------------------------------
    // Lesson 1 — Greetings & introductions
    // -------------------------------------------------------------------
    {
      id: "l-01-01",
      title: "Hallo! Ich heiße …",
      level: "A2",
      track: "personal",
      canDo: ["cd-introduce", "cd-ask-name"],
      grammar: ["g-sein-heissen", "g-w-fragen"],
      scenario: "sc-vorstellen",
      dialogue: [
        {
          speaker: "Anna",
          de: "Hallo! Ich heiße Anna. Und du?",
          en: "Hi! My name is Anna. And you?",
          vocab: ["v-heissen", "v-hallo"],
        },
        {
          speaker: "Ben",
          de: "Hallo Anna. Ich bin Ben. Freut mich!",
          en: "Hi Anna. I'm Ben. Nice to meet you!",
          vocab: ["v-sein", "v-freut-mich"],
        },
        {
          speaker: "Anna",
          de: "Woher kommst du, Ben?",
          en: "Where are you from, Ben?",
          vocab: ["v-woher", "v-kommen"],
        },
        {
          speaker: "Ben",
          de: "Ich komme aus Kanada. Und ich wohne jetzt in Wien.",
          en: "I'm from Canada. And I live in Vienna now.",
          vocab: ["v-wohnen"],
        },
      ],
      vocab: [
        { id: "v-hallo", de: "hallo", en: "hello", pos: "interjection", level: "A2" },
        {
          id: "v-heissen",
          de: "heißen",
          en: "to be called",
          pos: "verb",
          example: "Ich heiße Anna.",
          exampleEn: "My name is Anna.",
          level: "A2",
        },
        {
          id: "v-sein",
          de: "sein",
          en: "to be",
          pos: "verb",
          example: "Ich bin Ben.",
          exampleEn: "I am Ben.",
          level: "A2",
        },
        {
          id: "v-freut-mich",
          de: "Freut mich!",
          en: "Nice to meet you!",
          pos: "phrase",
          level: "A2",
        },
        {
          id: "v-woher",
          de: "woher",
          en: "where from",
          pos: "adverb",
          example: "Woher kommst du?",
          exampleEn: "Where are you from?",
          level: "A2",
        },
        {
          id: "v-kommen",
          de: "kommen (aus)",
          en: "to come (from)",
          pos: "verb",
          example: "Ich komme aus Kanada.",
          exampleEn: "I come from Canada.",
          level: "A2",
        },
        {
          id: "v-wohnen",
          de: "wohnen (in)",
          en: "to live (in)",
          pos: "verb",
          example: "Ich wohne in Wien.",
          exampleEn: "I live in Vienna.",
          level: "A2",
        },
      ],
      drills: [
        {
          id: "d-01-01-1",
          type: "gap-fill",
          text: "Ich ___ Anna.",
          answer: "heiße",
          translation: "My name is Anna.",
        },
        {
          id: "d-01-01-2",
          type: "conjugate",
          infinitive: "sein",
          person: "ich",
          tense: "Präsens",
          answer: "bin",
        },
        {
          id: "d-01-01-3",
          type: "reorder",
          tokens: ["Woher", "kommst", "du"],
          translation: "Where are you from?",
        },
        {
          id: "d-01-01-4",
          type: "gap-fill",
          text: "Ich ___ in Wien.",
          answer: "wohne",
          options: ["wohne", "wohnst", "wohnt"],
          translation: "I live in Vienna.",
        },
      ],
      shadow: [
        "Hallo! Ich heiße Anna.",
        "Freut mich!",
        "Woher kommst du?",
        "Ich komme aus Kanada.",
      ],
    },

    // -------------------------------------------------------------------
    // Lesson 2 — Ordering in a café
    // -------------------------------------------------------------------
    {
      id: "l-01-02",
      title: "Im Café",
      level: "A2",
      track: "personal",
      canDo: ["cd-order-cafe", "cd-accusative"],
      grammar: ["g-moechten", "g-akkusativ-artikel"],
      scenario: "sc-cafe",
      dialogue: [
        {
          speaker: "Kellner",
          de: "Guten Tag! Was möchten Sie?",
          en: "Good day! What would you like?",
          vocab: ["v-moechten"],
        },
        {
          speaker: "Gast",
          de: "Ich hätte gern einen Kaffee, bitte.",
          en: "I'd like a coffee, please.",
          vocab: ["v-haette-gern", "v-kaffee", "v-bitte"],
        },
        {
          speaker: "Kellner",
          de: "Gern. Mit Milch?",
          en: "Sure. With milk?",
          vocab: ["v-milch"],
        },
        {
          speaker: "Gast",
          de: "Nein, danke. Und die Rechnung, bitte.",
          en: "No, thanks. And the bill, please.",
          vocab: ["v-rechnung", "v-danke"],
        },
      ],
      vocab: [
        {
          id: "v-moechten",
          de: "möchten",
          en: "would like",
          pos: "verb",
          example: "Ich möchte einen Tee.",
          exampleEn: "I would like a tea.",
          level: "A2",
        },
        {
          id: "v-haette-gern",
          de: "hätte gern",
          en: "would like to have",
          pos: "phrase",
          example: "Ich hätte gern einen Kaffee.",
          exampleEn: "I'd like a coffee.",
          level: "A2",
        },
        {
          id: "v-kaffee",
          de: "der Kaffee",
          en: "coffee",
          pos: "noun",
          level: "A2",
        },
        { id: "v-milch", de: "die Milch", en: "milk", pos: "noun", level: "A2" },
        { id: "v-bitte", de: "bitte", en: "please", pos: "adverb", level: "A2" },
        { id: "v-danke", de: "danke", en: "thanks", pos: "adverb", level: "A2" },
        {
          id: "v-rechnung",
          de: "die Rechnung",
          en: "the bill",
          pos: "noun",
          example: "Die Rechnung, bitte.",
          exampleEn: "The bill, please.",
          level: "A2",
        },
      ],
      drills: [
        {
          id: "d-01-02-1",
          type: "case-choice",
          text: "Ich hätte gern ___ Kaffee.",
          options: ["der", "den", "einen"],
          answer: "einen",
          caseName: "Akkusativ",
          translation: "I'd like a coffee. (der Kaffee → einen)",
        },
        {
          id: "d-01-02-2",
          type: "gap-fill",
          text: "Ich ___ einen Tee, bitte.",
          answer: "möchte",
          options: ["möchte", "möchten", "will"],
          translation: "I'd like a tea, please.",
        },
        {
          id: "d-01-02-3",
          type: "reorder",
          tokens: ["Ich", "hätte", "gern", "einen", "Kaffee"],
          translation: "I'd like a coffee.",
        },
        {
          id: "d-01-02-4",
          type: "case-choice",
          text: "Ich nehme ___ Suppe. (die Suppe)",
          options: ["eine", "einen", "ein"],
          answer: "eine",
          caseName: "Akkusativ",
          translation: "I'll take a soup. (feminine stays 'eine')",
        },
      ],
      shadow: [
        "Ich hätte gern einen Kaffee, bitte.",
        "Mit Milch?",
        "Nein, danke.",
        "Die Rechnung, bitte.",
      ],
    },
  ],
};
